import "./globals.css";
// import { Atkinson_Hyperlegible } from "next/font/google";

// const body_font = Atkinson_Hyperlegible({
//   weight: ["400", "700"],
//   subsets: ["latin"],
// });

import { body_font } from "@/utils/font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${body_font.className} bg-neutral-100 text-zinc-800`}>
        {children}
      </body>
    </html>
  );
}
